# Generated by Django 3.1.5 on 2021-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User name.')),
                ('email', models.EmailField(max_length=254, verbose_name='User email.')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Quick Contact',
                'verbose_name_plural': 'Quick Contacts',
                'db_table': 'quick_contacts',
            },
        ),
    ]
